import os
import re
import datetime
from typing import Dict, Any


def _sanitize_domain_name(domain_name: str) -> str:
    """
    Sanitize a domain name for safe use inside a filesystem path segment.

    domain_name can originate from CLI input (or, in a live-AD run, from
    LDAP data) and is not guaranteed to be filesystem-safe. This whitelists
    alphanumerics, dots and hyphens (the valid characters in a DNS domain
    name) and replaces everything else (path separators, spaces, null
    bytes, "..", etc.) with an underscore, preventing path traversal or
    invalid-filename errors when the report file is created.
    """
    return re.sub(r"[^a-zA-Z0-9.\-]", "_", domain_name)


class ADReporter:
    """
    Generates professional Markdown audit reports for Active Directory
    and Windows security posture.
    """

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_report(self, domain_name: str, audit_result: Dict[str, Any]) -> str:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        safe_domain_name = _sanitize_domain_name(domain_name)
        filename = f"yggdrasil_audit_{safe_domain_name}_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)

        score = audit_result["score"]
        score_badge = "🔴 CRITICAL" if score < 50 else "🟡 WARNING" if score < 80 else "🟢 SECURE"

        content = f"""# Yggdrasil - Active Directory Security Audit Report

- **Domain**: `{domain_name}`
- **Scan Timestamp**: `{datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}`
- **Security Score**: `{score}/100` ({score_badge})
- **Total Findings**: `{audit_result['total_findings']}` (🔴 High: {audit_result['high_severity']} | 🟡 Medium: {audit_result['medium_severity']})

---

## Executive Summary

Yggdrasil performed an automated security posture assessment on domain `{domain_name}`. The analysis evaluated Active Directory password policies, account lockout configurations, and privileged user hygiene.

---

## Findings Breakdown

| Severity | Category | Title | Description |
|:---:|:---|:---|:---|
"""

        for f in audit_result["findings"]:
            sev_icon = "🔴" if f["severity"] == "HIGH" else "🟡"
            content += f"| {sev_icon} {f['severity']} | {f['category']} | **{f['title']}** | {f['description']} |\n"

        content += """
---

## Remediation Playbook

1. **Password Policies**: Enforce a minimum password length of at least 12 characters and enable complexity requirements across all domain GPOs.
2. **Privileged Accounts**: Disable 'Password Never Expires' for all Domain Admin and Enterprise Admin accounts. Implement Tiered Administration.
3. **Stale Accounts**: Identify and disable user and computer accounts inactive for more than 90 days.

---
*Generated by Yggdrasil Security Auditor - Asgard Suite*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath
